name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: unnecessary
      
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.8
        env:
          POSTGRES_USER = ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD = ${{ secrets.POSTGRES_PASSWORD }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          envs: POSTGRES_USER, POSTGRES_PASSWORD
          script: |
            git clone git@github.com:neklyud/pg_storage
            cd pg_storage
            docker-compose down
            docker-compose up -d --build
            ls -l
 