name: Build & Deploy
on:
  push:
    branches: [main]

env:
  POSTGRES_USER = ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD = ${{ secrets.POSTGRES_PASSWORD }}

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: unnecessary
      
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            export POSTGRES_USER=${{ env.POSTGRES_USER }}
            export POSTGRES_PASSWORD=${{ env.POSTGRES_PASSWORD }}
            git clone git@github.com:neklyud/pg_storage
            cd pg_storage
            docker-compose up -d
            ls -l
 